"""
gui/lang.py  — Language dictionary (migrate từ main.py LANG)
"""
LANG = {
    "vi": {
        "nav_monitor": "📊\nGiám sát", "nav_editor": "✏️\nBản đồ", "nav_manual": "🕹️\nĐiều khiển",
        "nav_stats": "📈\nThống kê", "nav_settings": "⚙️\nCài đặt",
        "tab_conn": "Kết nối", "tab_gen": "Chung", "tab_traffic": "Giao thông", "tab_bat": "Pin & Sạc",
        "tab_elv": "Thang máy", "tab_alarm": "Cảnh báo", "tab_user": "Người dùng", "tab_integ": "Tích hợp",
        "lbl_sys_config": "Cấu hình hệ thống",
        "lbl_net_set": "Cài đặt mạng", "lbl_wifi_ssid": "Tên WiFi:", "lbl_wifi_pass": "Mật khẩu:",
        "lbl_mqtt_broker": "MQTT Broker", "lbl_broker_ip": "IP Broker:", "lbl_port": "Cổng:",
        "lbl_user": "Tài khoản:", "lbl_pass": "Mật khẩu:",
        "tab_actions": "Nhiệm vụ (Actions)", "lbl_custom_actions": "Định nghĩa Nhiệm vụ Đặc biệt (Custom Actions)",
        "col_act_id": "Mã (ID)", "col_act_name": "Tên hiển thị", "btn_add_act": "Thêm Action", "btn_del_act": "Xóa Action",
        "btn_save_net": "Lưu cài đặt mạng",
        "lbl_agv_mgmt": "Quản lý AGV", "btn_add_agv": "➕ Thêm / Sửa", "btn_del_agv": "❌ Xóa chọn",
        "lbl_work_param": "Thông số làm việc", "lbl_work_hours": "Giờ làm việc/ngày (Max):",
        "lbl_dispatch_rule": "Luật điều phối (Ưu tiên)",
        "rule_nearest": "Gần nhất (Khoảng cách)", "rule_idle": "Rảnh nhất (Phân phối đều)", "rule_battery": "Pin cao (>20%)",
        "btn_save_gen": "Lưu cài đặt chung",
        "lbl_traffic_param": "Thông số giao thông", "lbl_safe_dist": "Khoảng cách an toàn (m):",
        "lbl_deadlock_time": "Timeout kẹt xe (s):",
        "lbl_speed_cfg": "Cấu hình Tốc độ (Auto)", "lbl_speed_fast": "Nhanh (Thẳng):", "lbl_speed_slow": "Chậm (Cua):",
        "btn_save_traffic": "Lưu cài đặt giao thông",
        "lbl_bat_mgmt": "Quản lý Pin", "chk_auto_charge": "Bật sạc tự động",
        "lbl_low_bat": "Ngưỡng pin yếu (%):", "lbl_resume_bat": "Ngưỡng làm lại (%):", "btn_save_bat": "Lưu cài đặt Pin",
        "lbl_elv_integ": "Tích hợp thang máy", "btn_add_elv": "Thêm/Sửa EIU",
        "lbl_err_mgmt": "Quản lý lỗi", "lbl_stuck_time": "Timeout kẹt (s):", "btn_save_alarm": "Lưu cấu hình cảnh báo",
        "lbl_active_err": "Lỗi hiện tại",
        "lbl_user_mgmt": "Quản lý người dùng", "btn_add_user": "Thêm người dùng",
        "lbl_sys_integ": "Tích hợp hệ thống (API)", "chk_enable_api": "Bật REST API Server",
        "lbl_api_port": "Cổng API:", "btn_save_integ": "Lưu cài đặt tích hợp",
        "btn_lang_toggle": "🌐 Ngôn ngữ: Tiếng Việt",
        "lbl_op_stats": "Thống kê hoạt động", "lbl_station_cfg": "Cấu hình tên trạm",
        "lbl_node_id": "ID Thẻ:", "lbl_disp_name": "Tên hiển thị:",
        "btn_save_name": "Lưu tên", "lbl_from": "Từ ngày:", "lbl_to": "Đến ngày:",
        "btn_refresh": "Làm mới", "btn_show_pass": "Hiện", "btn_hide_pass": "Ẩn",
        "btn_gen_data": "🎲 Tạo dữ liệu giả", "btn_clear_data": "🗑️ Xóa dữ liệu",
        "chart_time_dist": "Phân bố thời gian hoạt động",
        "chart_trips": "Số chuyến hoàn thành theo Trạm (Đã cấu hình)",
        "legend_click": "Nhấn vào ô màu để đổi:", "legend_trip_color": "Màu cột chuyến:",
        "col_id": "ID", "col_ip": "IP", "col_sub": "Topic Nhận", "col_pub": "Topic Gửi", "col_color": "Màu",
        "col_name": "Tên", "col_role": "Vai trò", "col_last_login": "Đăng nhập cuối",
        "col_err_code": "Mã lỗi", "col_desc": "Mô tả", "col_time": "Thời gian",
        "lbl_fleet_status": "Trạng thái đội xe", "col_status": "Trạng thái", "col_tag": "Thẻ", "col_rssi": "Sóng",
        "lbl_dispatcher": "Điều phối", "lbl_select_agv": "Chọn AGV:", "lbl_start_node": "Điểm bắt đầu:",
        "lbl_target_node": "Điểm đến:", "lbl_task_type": "Loại nhiệm vụ:",
        "btn_go": "Gửi Lệnh (Thủ công)", "btn_auto_dispatch": "🚀 Gọi xe tự động (MES Sim)",
        "lbl_manual": "Điều khiển tay:",
        "btn_run": "CHẠY", "btn_stop": "DỪNG", "btn_reset_agv": "🔄 Reset / Xóa lỗi",
        "btn_reverse": "⚠️ Lùi xe (Gỡ kẹt)",
        "lbl_map_editor": "Chỉnh sửa bản đồ", "lbl_next_id": "ID tiếp theo:",
        "btn_tool_select": "✋ Chọn / Di chuyển", "btn_tool_node": "➕ Thêm Thẻ (Click)",
        "btn_tool_edge": "🔗 Nối Thẻ (Kéo)", "btn_save_map": "💾 Lưu Map",
        "btn_save_as": "💾 Lưu mới...", "btn_load_map": "📂 Mở Map",
        "btn_undo": "↩ Hoàn tác", "btn_redo": "↪ Làm lại", "btn_tool_delete": "🗑️ Xóa đã chọn [Del]",
        "title_schedule": "Kế hoạch vận chuyển trong ngày",
        "lbl_homing_path": "Đường dẫn dò về trạm:", "lbl_homing_path_desc": "(VD: 1, 2, 3, 10)",
        "col_sch_time": "Giờ", "col_sch_target": "Đích đến", "col_sch_trips": "Số chuyến",
        "col_sch_status": "Trạng thái", "btn_add_task": "Thêm nhiệm vụ", "btn_del_task": "Xóa nhiệm vụ",
        "nav_schedule": "📅\nLịch trình", "nav_sim": "🔬\nMô phỏng", "nav_burnin": "🔄\nChạy thử",
        "nav_log": "📋\nSystem\nLog",
        "nav_login": "👤\nTài khoản",
        "lbl_login_title": "Đăng nhập hệ thống", "lbl_username": "Tên đăng nhập:", "lbl_password": "Mật khẩu:",
        "btn_login_action": "Đăng nhập", "msg_login_success": "Đăng nhập thành công!",
        "msg_login_fail": "Sai tên đăng nhập hoặc mật khẩu!",
        "msg_logout_confirm": "Bạn có chắc chắn muốn đăng xuất?", "lbl_trips": "Số chuyến:",
        "tab_stations": "Tổ/Trạm",
        "lbl_station_setup": "Cấu hình Tổ & Trạm",
        "col_team_id": "ID Tổ / Team ID", "col_wait_node": "Thẻ chờ / Wait Tag",
        "col_del_node": "Thẻ giao / Delivery Tag",
        "lbl_charger_setup": "Cấu hình Trạm Sạc",
        "col_chg_name": "Tên / Name", "col_chg_node": "Thẻ sạc / Node",
        "col_chg_zone": "Vùng lùi / Rev. Zone", "col_chg_speed": "Tốc độ chậm / Speed",
        "ed_title_node": "Sửa Node", "ed_node_id": "ID Node:", "ed_func": "Chức năng:",
        "ed_act_seq": "Chuỗi hành động:", "ed_save": "Lưu & Đóng",
        "ed_title_edge": "Sửa Tuyến đường", "ed_nav_main": "1. Điều hướng chính (Di chuyển)",
        "ed_task_spec": "2. Nhiệm vụ đặc biệt", "ed_start_act": "Tại điểm đầu", "ed_end_act": "Tại điểm cuối",
        "ed_create_conn": "➕ Tạo kết nối", "ed_no_conn": "(Chưa có kết nối)", "ed_save_change": "Lưu thay đổi",
    },
    "en": {
        "nav_monitor": "📊\nMonitor", "nav_editor": "✏️\nEditor", "nav_manual": "🕹️\nManual Ctrl",
        "nav_stats": "📈\nStats", "nav_settings": "⚙️\nSettings",
        "tab_conn": "Connection", "tab_gen": "General", "tab_traffic": "Traffic", "tab_bat": "Battery",
        "tab_elv": "Elevator (Disabled)", "tab_alarm": "Alarms", "tab_user": "Users", "tab_integ": "Integration",
        "lbl_sys_config": "System Configuration",
        "lbl_net_set": "Network Settings", "lbl_wifi_ssid": "WiFi SSID:", "lbl_wifi_pass": "Password:",
        "lbl_mqtt_broker": "MQTT Broker", "lbl_broker_ip": "Broker IP:", "lbl_port": "Port:",
        "lbl_user": "Username:", "lbl_pass": "Password:",
        "tab_actions": "Actions", "lbl_custom_actions": "Define Custom Actions",
        "col_act_id": "Code (ID)", "col_act_name": "Display Name", "btn_add_act": "Add Action", "btn_del_act": "Delete Action",
        "btn_save_net": "Save Network Settings",
        "lbl_agv_mgmt": "AGV Management", "btn_add_agv": "➕ Add / Update", "btn_del_agv": "❌ Delete Selected",
        "lbl_work_param": "Work Parameters", "lbl_work_hours": "Daily Work Hours (Max):",
        "lbl_dispatch_rule": "Dispatching Logic (Priority)",
        "rule_nearest": "Nearest AGV (Distance based)", "rule_idle": "Most Idle (Equal Distribution)",
        "rule_battery": "High Battery Priority (>20% required)",
        "btn_save_gen": "Save General & Control Settings",
        "lbl_traffic_param": "Traffic Control Parameters", "lbl_safe_dist": "Safety Distance (meters):",
        "lbl_deadlock_time": "Deadlock Check Timeout (s):",
        "lbl_speed_cfg": "Auto Speed Config", "lbl_speed_fast": "Fast (Straight):", "lbl_speed_slow": "Slow (Turn):",
        "btn_save_traffic": "Save Traffic Settings",
        "lbl_bat_mgmt": "Battery Management System", "chk_auto_charge": "Enable Auto-Charging Logic",
        "lbl_low_bat": "Low Battery Threshold (%):", "lbl_resume_bat": "Resume Work Threshold (%):",
        "btn_save_bat": "Save Battery Settings",
        "lbl_elv_integ": "Elevator Integration", "btn_add_elv": "Add/Update EIU",
        "lbl_err_mgmt": "Error Management", "lbl_stuck_time": "Stuck Timeout (seconds):",
        "btn_save_alarm": "Save Alarm Config",
        "lbl_active_err": "Active Errors (Real-time)",
        "lbl_user_mgmt": "User Management", "btn_add_user": "Add User",
        "lbl_sys_integ": "System Integration (API)", "chk_enable_api": "Enable REST API Server",
        "lbl_api_port": "API Port:", "btn_save_integ": "Save Integration Settings",
        "btn_lang_toggle": "🌐 Language: English",
        "lbl_op_stats": "Operational Statistics", "lbl_station_cfg": "Station Naming & Config",
        "lbl_node_id": "Node ID:", "lbl_disp_name": "Display Name:",
        "btn_save_name": "Save Name", "lbl_from": "From:", "lbl_to": "To:",
        "btn_refresh": "Refresh Charts", "btn_show_pass": "Show", "btn_hide_pass": "Hide",
        "btn_gen_data": "🎲 Generate Simulation Data", "btn_clear_data": "🗑️ Clear Data",
        "chart_time_dist": "AGV Work Time Distribution",
        "chart_trips": "Completed Trips per Station/Team (Only Configured Stations)",
        "legend_click": "Click color box to change:", "legend_trip_color": "Trip Bar Color:",
        "col_id": "ID", "col_ip": "IP", "col_sub": "Sub Topic", "col_pub": "Pub Topic", "col_color": "Color",
        "col_name": "Name", "col_role": "Role", "col_last_login": "Last Login",
        "col_err_code": "Error Code", "col_desc": "Description", "col_time": "Time",
        "lbl_fleet_status": "AGV Fleet Status", "col_status": "Status", "col_tag": "Tag", "col_rssi": "RSSI",
        "lbl_dispatcher": "Dispatcher", "lbl_select_agv": "Select AGV:", "lbl_start_node": "Start Node:",
        "lbl_target_node": "Target Node:", "lbl_task_type": "Task Type:",
        "btn_go": "Dispatch (Manual)", "btn_auto_dispatch": "🚀 Auto Dispatch (MES Sim)",
        "lbl_manual": "Manual Override:",
        "btn_run": "RUN", "btn_stop": "STOP", "btn_reset_agv": "🔄 Reset / Clear Error",
        "btn_reverse": "⚠️ Force Reverse (Deadlock)",
        "lbl_map_editor": "Map Editor", "lbl_next_id": "Next ID:",
        "btn_tool_select": "✋ Select / Move", "btn_tool_node": "➕ Add Node (Click)",
        "btn_tool_edge": "🔗 Connect (Drag)", "btn_save_map": "💾 Save Map",
        "btn_save_as": "💾 Save As...", "btn_load_map": "📂 Load Map",
        "btn_undo": "↩ Undo", "btn_redo": "↪ Redo", "btn_tool_delete": "🗑️ Delete Selected [Del]",
        "title_schedule": "Daily Transport Plan",
        "lbl_homing_path": "Homing Beacon Path:", "lbl_homing_path_desc": "(e.g. 1, 2, 3, 10)",
        "col_sch_time": "Time", "col_sch_target": "Target", "col_sch_trips": "Trips",
        "col_sch_status": "Status", "btn_add_task": "Add Task", "btn_del_task": "Delete Task",
        "nav_schedule": "📅\nSchedule", "nav_sim": "🔬\nSimulate", "nav_burnin": "🔄\nBurn-in",
        "nav_log": "📋\nSystem\nLog",
        "nav_login": "👤\nAccount",
        "lbl_login_title": "System Login", "lbl_username": "Username:", "lbl_password": "Password:",
        "btn_login_action": "Login", "msg_login_success": "Login Successful!",
        "msg_login_fail": "Invalid username or password!",
        "msg_logout_confirm": "Are you sure you want to logout?", "lbl_trips": "Trips:",
        "tab_stations": "Tổ/Trạm (Stations)",
        "lbl_station_setup": "Cấu hình Tổ & Trạm / Team & Station Config",
        "col_team_id": "ID Tổ / Team ID", "col_wait_node": "Thẻ chờ / Wait Tag",
        "col_del_node": "Thẻ giao / Delivery Tag",
        "lbl_charger_setup": "Cấu hình Trạm Sạc / Charging Station Config",
        "col_chg_name": "Tên / Name", "col_chg_node": "Thẻ sạc / Node",
        "col_chg_zone": "Vùng lùi / Rev. Zone", "col_chg_speed": "Tốc độ chậm / Speed",
        "ed_title_node": "Edit Node", "ed_node_id": "Node ID:", "ed_func": "Function:",
        "ed_act_seq": "Actions Sequence:", "ed_save": "Save & Close",
        "ed_title_edge": "Edit Route", "ed_nav_main": "1. Main Navigation (Movement)",
        "ed_task_spec": "2. Special Tasks Sequence", "ed_start_act": "At Start", "ed_end_act": "At End",
        "ed_create_conn": "➕ Create Connection", "ed_no_conn": "(No connection)", "ed_save_change": "Save Changes",
    }
}
